name: build test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - feature/*
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
      - name: Build
        run: |
          cargo build
      - name: Format
        run: |
          cargo fmt --all -- --check
      - name: Clippy
        run: |
          cargo clippy --all -- -D warnings
      - name: Test
        run: |
          cargo test -- --test-threads=1
